platform :ios, '9.0'

inhibit_all_warnings!

use_frameworks!

target 'CurrencyConverter' do
    pod 'Alamofire', '4.8.0'
    pod 'AlamofireNetworkActivityIndicator', '~> 2.4'
    pod 'IQKeyboardManagerSwift'
    pod 'MBProgressHUD'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
            config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '5.1'
            if config.name == 'Release'
                config.build_settings['ASSETCATALOG_COMPILER_OPTIMIZATION'] = 'space'
                config.build_settings['GCC_FAST_MATH'] = 'YES'
                config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 's'
                config.build_settings['LLVM_LTO'] = 'YES'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
            else
                config.build_settings['ASSETCATALOG_COMPILER_OPTIMIZATION'] = ''
                config.build_settings['GCC_FAST_MATH'] = 'NO'
                config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
                config.build_settings['LLVM_LTO'] = 'YES_THIN'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
            end
        end
    end
end
